apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: boutique

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
<<<<<<< HEAD
          image: 995938832906.dkr.ecr.ap-south-1.amazonaws.com/frontend:94f6c4964430a8219b726c5deaaf55161b6ae0a9
=======
          image: 995938832906.dkr.ecr.ap-south-1.amazonaws.com/frontend:94f6c4964430a8219b726c5deaaf55161b6ae0a9
>>>>>>> 8b3ebc3 (initial ai devsecops setup)

          ports:
            - containerPort: 3000

          env:
            - name: REACT_APP_API_URL
              value: "http://gateway:3001/api"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: boutique

spec:
  selector:
    app: frontend

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

  type: ClusterIP