apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth
  namespace: boutique

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - sh
            - -c
            - >
              until nc -z boutique-postgres 5432;
              do
                echo waiting for postgres;
                sleep 5;
              done;

      containers:
        - name: auth
          image: 995938832906.dkr.ecr.ap-south-1.amazonaws.com/auth:b84e91fbdfed603d1ab930f31dd6dbd81927f280

          ports:
            - containerPort: 3002

          env:
            - name: NODE_ENV
              value: development

            - name: PORT
              value: "3002"

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: boutique-secrets
                  key: AUTH_DB_URL

          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service

metadata:
  name: auth
  namespace: boutique

spec:
  selector:
    app: auth

  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002

  type: ClusterIP