apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: boutique

spec:
  replicas: 1

  selector:
    matchLabels:
      app: gateway

  template:
    metadata:
      labels:
        app: gateway

    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - sh
            - -c
            - >
              until nc -z boutique-postgres 5432;
              do
                echo waiting for postgres;
                sleep 5;
              done;

      containers:
        - name: gateway
<<<<<<< HEAD
          image: 995938832906.dkr.ecr.ap-south-1.amazonaws.com/gateway:1daaf9370c4b96f2b7976cb56d4cbb7fc4fd8ef0
=======
          image: 995938832906.dkr.ecr.ap-south-1.amazonaws.com/gateway:1daaf9370c4b96f2b7976cb56d4cbb7fc4fd8ef0
>>>>>>> 8b3ebc3 (initial ai devsecops setup)

          ports:
            - containerPort: 3001

          env:
            - name: NODE_ENV
              value: development

            - name: PORT
              value: "3001"

            - name: AUTH_SERVICE_URL
              value: "http://auth:3002"

            - name: PRODUCTS_SERVICE_URL
              value: "http://product-service:3003"

            - name: ORDER_SERVICE_URL
              value: "http://order-service:3004"

            - name: ORDERS_SERVICE_URL
              value: "http://orders:3005"

            - name: USERS_SERVICE_URL
              value: "http://user-service:3006"

          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service

metadata:
  name: gateway
  namespace: boutique
  labels:
    app: gateway

spec:
  selector:
    app: gateway

  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001

  type: ClusterIP