apiVersion: apps/v1
kind: Deployment

metadata:
  name: order-service
  namespace: boutique

spec:
  replicas: 1

  selector:
    matchLabels:
      app: order-service

  template:
    metadata:
      labels:
        app: order-service

    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - sh
            - -c
            - >
              until nc -z boutique-postgres 5432;
              do
                echo waiting for postgres;
                sleep 5;
              done;

      containers:
        - name: order-service
<<<<<<< HEAD
          image: 995938832906.dkr.ecr.ap-south-1.amazonaws.com/order-service:15c2fe53e6f0006b225b44ff3e23a58ed2c44a41
=======
          image: 995938832906.dkr.ecr.ap-south-1.amazonaws.com/order-service:latest
>>>>>>> 8b3ebc3 (initial ai devsecops setup)

          ports:
            - containerPort: 3004

          env:
            - name: NODE_ENV
              value: development

            - name: PORT
              value: "3004"

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: boutique-secrets
                  key: ORDERS_DB_URL

            - name: AUTH_SERVICE_URL
              value: "http://auth:3002"

            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:3003"

          livenessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 3004
            initialDelaySeconds: 10
            periodSeconds: 5

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service

metadata:
  name: order-service
  namespace: boutique

spec:
  selector:
    app: order-service

  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004

  type: ClusterIP